options:
  dcf_path: "@BUS_CONFIG_PATH@" #install/microphase_can_config/share/microphase_can_config/config/bus_config

master:
  node_id: 1
  package: canopen_master_driver
  driver: ros2_canopen::MasterDriver

echo_slave:
  node_id: 2
  dcf: "TRACTION_PWR.eds"
  package: canopen_proxy_driver
  driver: ros2_canopen::ProxyDriver
  polling: true
  period: 10
  namespace: "/test1"
