services:
  ros2_jazzy:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
      tags:
        - ros2-canbus-nvidia:latest
      target: app
      args:
        - BASE_DOCKER_IMAGE=osrf/ros:jazzy-desktop-full
        - WORKSPACE=/home/ubuntu/ros_ws
        - network=host
    container_name: ros2_jazzy_nvidia
    volumes:
      # Mount /dev for device access
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: ../../
        target: /home/ubuntu/ros_ws
      # X11 forwarding for Xorg
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        consistency: cached
      # Wayland support
      - type: bind
        source: ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
        target: ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
        consistency: cached
        read_only: false
      - type: bind
        source: /run/user
        target: /run/user
      # Intel GPU support (for hybrid systems)
      - type: bind
        source: /dev/dri
        target: /dev/dri
    privileged: true
    network_mode: host
    # Device access for USB devices
    device_cgroup_rules:
      - 'c 188:* rmw'  # Allow access to USB serial devices (ttyUSB*)
      - 'c 166:* rmw'  # Allow access to ACM devices (ttyACM*)
    # NVIDIA GPU support
    runtime: nvidia
    ipc: host
    tty: true
    cap_add:
      - SYS_PTRACE
    group_add:
      - tty
      - audio
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    environment:
      - "TERM=xterm-256color"
      # Display environment variables
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - XDG_SESSION_TYPE=${XDG_SESSION_TYPE}
      - XAUTHORITY=$XAUTHORITY
      - QT_QPA_PLATFORM=xcb
      - GDK_BACKEND=wayland
      - MOZ_ENABLE_WAYLAND=1
      - QT_X11_NO_MITSHM=1
      # NVIDIA specific
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
      - LIBGL_ALWAYS_SOFTWARE=0
      # ROS specific
      - ROS_DOMAIN_ID=42
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
    # Command to keep container running for dev containers
    command: sleep infinity
