
options:
  dcf_path: "@BUS_CONFIG_PATH@"
  
master:
  node_id: 1
  driver: canopen_master_driver
  baudrate: 1000000  # Match your bridge CAN baud rate

nodes:
  front_left_traction:
    node_id: 2
    driver: canopen_proxy_driver
    dcf: eds/TRACTION_PWR.eds
  front_left_steer:
    node_id: 3
    driver: canopen_proxy_driver
    dcf: eds/TRACTION_PWR.eds
  rear_right_traction:
    node_id: 4
    driver: canopen_proxy_driver
    dcf: eds/TRACTION_PWR.eds
  rear_right_steer:
    node_id: 5
    driver: canopen_proxy_driver
    dcf: eds/TRACTION_PWR.eds
