services:
  ros2_jazzy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      tags:
        - latest
      target: app
      args:
        - BASE_DOCKER_IMAGE=osrf/ros:jazzy-desktop-full
        - WORKSPACE=/home/ros/ros_ws
        - network=host
    container_name: ros2_jazzy
    volumes:
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: ../
        target: /home/ros/ros_ws
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: false
      - type: bind
        source: ${HOME}/.Xauthority
        target: /tmp/.host_xauth
        read_only: true
      # uncomment the following line if you want to use the WSLg GUI
      # - type: bind
      #   source: /mnt/wslg
      #   target: /mnt/wslg
      # uncomment to use intel iGPU
      - type: bind
        source: /dev/dri
        target: /dev/dri
      #- type: bind
      #  source: ./LivoxViewer2
      #  target: /ros_ws/LivoxViewer2
      - type: bind
        source: /run/user/1000
        target: /run/user/1000
    privileged: true
    network_mode: host
    # Mount all devices via /dev volume above instead of specific devices
    # This ensures all USB devices are available regardless of enumeration order
    device_cgroup_rules:
      - 'c 188:* rmw'  # Allow access to USB serial devices (ttyUSB*)
      - 'c 166:* rmw'  # Allow access to ACM devices (ttyACM*)
    runtime: nvidia
    ipc: host
    tty: true
    stdin_open: true
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN  # Additional capability for device access
    group_add:
      - dialout    # Essential group for serial device access
      - tty
      - audio
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/ros/.Xauthority
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - RCUTILS_COLORIZED_OUTPUT=1
      - TERM=xterm-256color
      - LIBGL_ALWAYS_INDIRECT=0
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    command: bash -c "cp /tmp/.host_xauth /home/ros/.Xauthority 2>/dev/null || true; chmod 600 /home/ros/.Xauthority 2>/dev/null || true; sleep infinity"