options:
  dcf_path: "@BUS_CONFIG_PATH@"
  can_interface_name: "vcan0" # Virtual CAN interface from USB-CAN bridge

master:
  node_id: 1
  package: canopen_master_driver
  driver: ros2_canopen::MasterDriver

test_motor:
  node_id: 2
  dcf: "test_motor.eds" # Simplified EDS for testing
  package: canopen_proxy_driver
  driver: ros2_canopen::ProxyDriver
  polling: false
  period: 10
  heartbeat_consumer: true
  heartbeat_producer: 1000
  mandatory_slave_heartbeat: 2000

  # TPDO configuration (status from motor)
  tpdo1:
    enabled: true
    cob_id: "auto"
    transmission: 0x01
    mapping:
      - { index: 0x6041, sub_index: 0x00 } # Status word
      - { index: 0x606C, sub_index: 0x00 } # Velocity actual value
      - { index: 0x6064, sub_index: 0x00 } # Position actual value

  # RPDO configuration (commands to motor)
  rpdo1:
    enabled: true
    cob_id: "auto"
    transmission: 0x01
    mapping:
      - { index: 0x6040, sub_index: 0x00 } # Control word
      - { index: 0x60FF, sub_index: 0x00 } # Target velocity
